### ISSUE TITLE
About Supervised loss and consistency loss

### ISSUE THREAD

**Issue by RzzzLiu** [xiaoyao3302/CCVC#8]
Hi, thank you very much for your excellent work. I would like to ask you a few questions. When I was doing the ablation experiment, I found that if the unsupervised part of the loss is not added, there is only supervised loss, but the iou_ave is higher, but the problem here is that although the obtained iou_ave is higher , but the individual iou of the two branches is not high, and the value of both of them is very different from the average iou_ave, such as 
[2023-08-29 18:01:01,619][ INFO] ***** Evaluation with branch 1 original ***** >>>> meanIOU: 58.85
[2023-08-29 18:01:01,619][ INFO ] ***** Evaluation with branch 2 original ***** >>>> meanIOU: 58.63
[2023-08-29 18:01:01,620][ INFO ] ***** Evaluation with two branches original ***** >>>> meanIOU: 60.27

But if I add the consistency loss,
[2023-08-29 14:20:26,233][ INFO ] ***** Evaluation with branch 1 original ***** >>>> meanIOU: 58.76
[2023-08-29 14:20:26,233][ INFO ] ***** Evaluation with branch 2 original ***** >>>> meanIOU: 58.73
[2023-08-29 14:20:26,233][ INFO ] ***** Evaluation with two branches original ***** >>>> meanIOU: 59.19

We can know that after the consistency loss is added below, the iou of the obtained branch is obviously higher, but the iou_ave is not only the unsupervised iou_ave. What is the reason for this? I guess it may be related to the way of evaluate. May I ask if you also encountered this problem during the experiment. Looking forward to your reply, much appreciated.

**Comment by xiaoyao3302** [comment]
Hi, thanks for your attention. The iou_ave is calculated using pred_ave = (pred1 + pred2) / 2, please refer to valid_save.py for more details. Yes, we come across the situation that iou_ave is higher than a single branch, the reason is that the pred_ave can be treated as the voting result of two branches, which may lead to a more stable and accurate result. Please note that we only report the results using branch 1, and please refer to our provided log.txt for more details. As for your ablation, I'm a little puzzled about your results, please make sure that you conduct your experiments on the Pascal VOC dataset under the partition of 1/4, as we can see, your results are a bit lower than our results, including both the supervised baseline and using the consistency loss. Based on my observation, the consistency loss will greatly improve the performance. If you have any other questions, please feel free to ask.

**Comment by RzzzLiu** [comment]
你好，我正在follow你的工作，我用的数据集是遥感图像的分割。就是我的消融实验是直接在计算总损失的时候去掉loss_con和loss_dis，只让loss=loss_ce，但是去掉这些无监督损失反而iou_ave更高了，但是更让人困惑的是在只有有监督损失时，假如两个分支的iou分别为58.5, 58.7，它们得到的iou_ave 就会很轻松达到60.，而如果加了无监督的损失后,假如两个分支的iou分别为58.5, 58.7,它们的iou_ave却只能达到58.9这样，感觉非常的奇怪。我已经试了很多次，并且确保了数据集划分没问题

**Comment by RzzzLiu** [comment]
希望您能给我一些建议，关于应该如何正确的去做CCVC的消融实验

**Comment by xiaoyao3302** [comment]
我对遥感图像不是很了解，或许你可以比较一下两支网络的pred，看一看不一致的预测的占比，因为consistency主要是为了利用unlabeled data，但是如果labeled data已经足够的话，举一个极端的例子，两支网络的预测会完全一致，这时候consistency应该是不会起到作用的。你可以试着把discrepancy也加上比较一下结果，因为discrepancy是强行让两支网络学到的东西不一致，但是我不确定这在遥感图像上会不会带来一个过强的扰动导致结果降低。

**Comment by xiaoyao3302** [comment]
另外，你在做consistency的时候有没有加augmentation？一般来说模型会从conflict的pred学到东西，而weak aug的pred相对来说会比strong aug要稳定，因此用weak aug的pred作为strong aug的监督信号会让模型学到更多semantics，你也可以试一下。

**Comment by RzzzLiu** [comment]
我现在在用pascal 数据集实验，我认为出错的原因很可能是我们之前改成了用单卡来跑，没用分布式训练，和无标签数据的采样有关，我现在用4卡分布式来训练，数据集也用pascal，请问您pascal数据集的lr_backbone和lr_network 分别设置的为多少呢？我想复现出一个良好的效果，谢谢您

**Comment by xiaoyao3302** [comment]
base lr是0.001 然后backbone的lr是1x (0.001) segmentation head的lr是10x (0.01) 就按照代码里的来就行

**Comment by xiaoyao3302** [comment]
然后多卡并行这玩意挺能提点的……嗯……

**Comment by RzzzLiu** [comment]
谢谢您，我现在试验出来了，确实是因为多卡的问题，我还有一个小疑惑，就是您论文最终的评价是选取用iou_ave的还是选择用branch中最高的iou那个，因为我发现纯有监督他经常就是两个分支57. 57.，最后iou_ave投票出来却能达到59.多，但是一般加了无监督损失后，两个分支都是58.多，投票出来也只能多0.几个点。希望这个您能给我指点一下，非常感谢您的杰出工作和您热心的回答。

**Comment by RzzzLiu** [comment]
我刚查看了，明白了，您的投票出来的iou_ave并不是您论文里的结果，只要选取其中较高的branch的作为pre，所以iou_ave并没有实质性的作用。谢谢您的工作，非常感谢

**Comment by xiaoyao3302** [comment]
你可以加一点aug试一试
